"""============================================================================
Project Euler 29

How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and
2 <= b <= 100?
============================================================================"""

def main():

    sequence = []
    for a in range(2,101):
        for b in range(2, 101):
            sequence.append(a**b)
    return len(sorted(list(set(sequence))))
